#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @File  : messagBorad.py
# @Author: tupurp
# @Date  : 2018/8/25 22:58
# @Desc  :对QQ好友的留言板进行词云生成
# wordCloud不支持中文字体
# 请自行百度替换字体文件，此处参考如下
# https://blog.csdn.net/Dick633/article/details/80261233
from os import path
from scipy.misc import imread
import matplotlib.pyplot as plt
from wordcloud import WordCloud
#当前文件所在路径
d=path.dirname(__file__)
inFile="tencent10.txt"
back_coloring_path = "background.png"
back_coloring = imread(path.join(d, back_coloring_path))

text=open(path.join(d,inFile),encoding="utf-8").read()
wordcloud=WordCloud(
               background_color="white",  # 背景颜色
               max_words=200,  # 词云显示的最大词数
               mask=back_coloring,  # 设置背景图片
               max_font_size=300,  # 字体最大值
               random_state=42,
               width=3000, height=1854, margin=2,# 设置图片默认的大小,但是如果使用背景图片的话,那么保存的图片大小将会按照其大小保存,margin为词语边缘距离
               ).generate(text)
plt.imshow(wordcloud)
plt.axis("off")
plt.figure()
plt.show()
wordcloud.to_file(path.join(d, "WordCloud.png"))

